version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
workflows:
  build-and-test:
    jobs: 
      - compile

jobs:
  compile:
    docker:
      - image: gcc8
    steps:
      - checkout
      - run:
          name: Updating Packages
          command: 'apt-get update'
      - run:
          name: Installing CMake
          command: 'apt-get install -y cmake'
      - run:
          name: Creating Build Files
          command: 'cmake -S. -Bbuild/circleci -DDEVOPT_EXCLUDE_PRETEST_FROM_ALL=On'
      - run:
          name: Building All
          command: 'cmake --build build/circleci -j 2'

#  - codecov/upload:
#          file: {{ coverage_report_filepath }}