version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  build-tools: circleci/build-tools@2.6.3
referenced:
  defaults: &defaults
    docker:
      - image: circleci/python:3.8.2-buster
  dependencies: &dependencies
    run:
      name: Dependencies
      command: |
        pwd
        sudo apt-get install -y rsync
        sudo python -m pip install --upgrade pip
        sudo python -m pip install scikit-ci-addons
        sudo ci_addons circle/install_cmake.py 3.17.1
      working_directory: '~/'
workflows:
  build-and-test:
    jobs: 
      - compile
      - test:
          requires:
            - compile
jobs:
  compile:
    <<: *defaults
    steps:
      - *dependencies
      - checkout
      - run:
          name: Update Git Submodules
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Creating Build Files
          command: 'cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DDEVOPT_ENABLE_COVERAGE_REPORT=On'
      - run:
          name: Building All
          command: 'cmake --build build -j 2'
      - persist_to_workspace:
          root: ./
          paths: ./
  test:
    <<: *defaults
    steps:
      - *dependencies
      - attach_workspace:
          at: ./
      - run:
          name: Running Tests
          command: ctest -V -j 2 -T Test
          working_directory: build
      - run:
          name: Converting Test Output
          command: |
            mkdir -p /tmp/test-results/CTest
            ci_addons ctest_junit_formatter > /tmp/test-results/CTest/results.xml
      - store_test_results:
          path: /tmp/test-results
