version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  build-tools: circleci/build-tools@2.6.3
referenced:
  defaults: &defaults
    docker:
      - image: circleci/python:3.8.2-buster
  dependencies: &dependencies
    run:
      name: Dependencies
      command: |
        sudo apt-get install -y rsync
        sudo python -m pip install --upgrade pip
        sudo python -m pip install scikit-ci-addons
        sudo ci_addons circle/install_cmake.py 3.17.1
workflows:
  build-and-test:
    jobs: 
      - compile
      - test:
          requires:
            - compile
jobs:
  compile:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Update Git Submodules
          command: |
            git submodule sync
            git submodule update --init
      - *dependencies
      - run:
          name: Creating Build Files
          command: 'cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DDEVOPT_ENABLE_COVERAGE_REPORT=On'
      - run:
          name: Building All
          command: 'cmake --build build -j 2'
      - persist_to_workspace:
          root: ./
          paths: ./
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - *dependencies
      - run:
          name: Running Tests
          command: |
            cd build
            ctest -V -j 2 -T Test
      - run:
          name: Converting Test Output
          command: |
            mkdir ${CIRCLE_TEST_REPORTS}/CTest
            ci_addons ctest_junit_formatter BUILD_DIR > ${CIRCLE_TEST_REPORTS}/CTest/JUnit-${CIRCLE_NODE_INDEX}.xml
